import Head from 'next/head'

export function Tab(props) {
  return (
    <Head>
      <title>Create Next App - {props.page}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
