import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Links } from '../components/links.js'
import { Footer } from '../components/footer.js'
import { Headline } from '@/components/headline.js'
import { Logo } from '@/components/logo.js'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Headline page='index'/>
        <Logo />
        <Links />
      </main>
      <Footer />
    </>
  )
}
